version: "3.1"
services:
    cpuload:
      build: 
        context: .
      container_name: cpuload
      working_dir: /src
      environment:
        - LS_DURATION=30
        - LS_LOADCPU=50
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
